### DISCUSSION TITLE
Baby buddy & Cloudflare tunnels

### DISCUSSION THREAD

**Discussion by patrickdass93** [babybuddy/babybuddy#964] [Q&A] [answered]
Hi, I can't seem to access babybuddy through a cloudflare tunnel.
What am I doing wrong?
```
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    volumes:
      - babybuddy:/config
    ports:
      - 2229:8000
    restart: unless-stopped
    environment:
      - TZ=Asia/Kuala_Lumpur
      - CSRF_TRUSTED_ORIGINS=https://babybuddy.example.com
    networks:
      - pi

networks:
  pi:
    driver: bridge
    name: docker_pi

volumes:
  babybuddy:
    driver: local
    driver_opts:
      type: none
      device: /home/Docker/babybuddy
      o: bind
```
<img width="650" alt="image" src="https://github.com/user-attachments/assets/50fbae98-e4b5-4650-a961-176c287cae2f" />
