### ISSUE TITLE
Home Assistant - Rest command to log feeding

### ISSUE THREAD

**Issue by Borlean** [babybuddy/babybuddy#586]
So I'm using a rest command in Home Assistant to log feeding and it works except for the amount. 

Software Versions: 
BabyBuddy v1.13.2 
Home Assistant 2023.1.1 Supervisor 2022.12.1 Operating System 9.4

```
rest_command:
  liquids:
    url: "http://192.168.1.87:8020/api/feedings/"
    verify_ssl: False #manually added
    method: post
    headers:
      authorization: "Token [API TOKEN]"
    payload: '{"child":"1", "start":"{{ now() - timedelta(seconds=60) }}", "end": "{{ now() }}", "type": "{{ feeding_type }}", "method":"{{ feeding_method }}", "amount": "{{ amount }}"}'
    content_type: "application/json"
```
The script being used by the REST command is as follows:

```
alias: "Babybuddy: Feeding"
sequence:
  - service: rest_command.liquids
    data:
      feeding_type: formula
      feeding_method: bottle
      amount: 8
  - service: notify.gotify_1
    data:
      title: Log feeding
      message: log feeding
mode: single
icon: mdi:baby-bottle-outline
```
Like i said, it'll add a feeding, but it won't include the amount. I believe there is something wrong with the last 'payload' argument in the rest_command (which is in the HA config file", but wasn't sure if anyone here knows how HA works with BB.
