### ISSUE TITLE
Non-staff users get 403 error unless given superuser privileges

### ISSUE THREAD

**Issue by lenaxia** [babybuddy/babybuddy#605]
Hi, current setup is traefik+authelia using forward auth header to login. When logging in with a new user, they receive 403 permission denied by default. Even after enabling them as staff they are unable to use BB. Only after going into admin and enabling super user status are they able to even access basic features of BB. 

Using helm but the important part is:
```
  values:
    image:
      repository: lscr.io/linuxserver/babybuddy
      tag: 1.14.0
    env:
      TZ: ${TIMEZONE}
      PGID: 1000
      PUID: 1000
      CSRF_TRUSTED_ORIGINS: http://127.0.0.1:8000,https://baby.${SECRET_DEV_DOMAIN}
      USE_24_HOUR_TIME_FORMAT: true
      ALLOWED_HOSTS: baby.${SECRET_DEV_DOMAIN}
      REVERSE_PROXY_AUTH: true
```
