### ISSUE TITLE
Time spans on the timeline page seem 2 years out

### ISSUE THREAD

**Issue by jberlyn** [babybuddy/babybuddy#673]
I recently started using BabyBuddy and noticed that the times on the timespan section for each child seem to show almost 2 years back as a negative number.

![image](https://github.com/babybuddy/babybuddy/assets/10014944/b6a7703b-6d97-42db-a2d6-0ebf65a8eea3)

I'm running v1.16.0 using Docker Compose.

Here is my Docker Compose file:

```yaml
  babybuddy:
    container_name: babybuddy
    image: lscr.io/linuxserver/babybuddy:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /mnt/storage/containers/babybuddy/config:/config
```
