### ISSUE TITLE
Forbidden (403) CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by Lockie85** [babybuddy/babybuddy#946]
Hey,

After restoring a backup I'm getting this issue:

```
Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.

More information is available with DEBUG=True.
```

I've not disabled cookies so I think the error might be misleading. Any thoughts?

Many Thanks

**Comment by skjdghsdjgsdj** [comment]
As a guess, when you restored the backup, did you restore your environment variables and `CSRF_TRUSTED_ORIGINS` and `ALLOWED_HOSTS` in particular?

**Comment by Lockie85** [comment]
I've no idea, I certain didn't see an option for those specific things.

**Comment by skjdghsdjgsdj** [comment]
I'm not sure how you installed Baby Buddy, so how the environment variables get set up can vary.

But here are the docs on the variables and what they mean:
https://docs.baby-buddy.net/configuration/security/#cors_allowed_origins

And here are the docs for the various deployment options:
https://docs.baby-buddy.net/setup/deployment/

For example, I have Baby Buddy deployed through Docker so here's what my `docker-compose.yml` looks like, obviously with sensitive data censored:

```
version: "2.6"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    environment:
      - TZ=...
      - CSRF_TRUSTED_ORIGINS=...
      - ALLOWED_HOSTS=...
      - PROXY_HEADER=HTTP_X_AUTHENTIK_USERNAME
      - REVERSE_PROXY_AUTH=True
    volumes:
      - /root/babybuddy/appdata:/config
    ports:
      - 8000:8000
    restart: unless-stopped
```

It's a pretty basic setup, although I'm using [Authentik](https://github.com/goauthentik/authentik) for logins, hence the extra `PROXY_HEADER` and `REVERSE_PROXY_AUTH` variables.

**Comment by kylewilliams321** [comment]
I'm also getting this issue however the comment pointing to variables does show what we probably need to update. However, where do you find and set these variables? They are not in the configuration screen? 

I'm using the home assistant add on.

**Comment by cdubz** [comment]
@Lockie85 have you managed to get your restored instance working again?

**Comment by Lockie85** [comment]
Hey, sorry I stopped trying as the issue occured when I was looking to migrate my Home Assistant instance, but I've decided against it. I didn't say anything else as it looked like the thread was still helping other people. But for myself I've no more to feedback, but thank you for the replies on my perspective.

**Comment by kylewilliams321** [comment]
I'm still having troubles

**Comment by wernerhp** [comment]
Also getting the CSRF issue with the Home Assistant Add-on.  

First I get
```
403: Forbidden
CSRF verification failed. Request aborted. Origin checking failed - https://my.domain.tld does not match any trusted origins.
How to Fix
Add https://my.domain.tld to the CSRF_TRUSTED_ORIGINS environment variable. If multiple origins are required separate with commas.
```

Then after adding 
```
Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.

More information is available with DEBUG=True.
```

Same on Brave and Firefox

https://my.domain.tld68152197_baby_buddy/ingress

When I set a network port, I can hit it on the IP e.g. http://192.168.1.1:8889/welcome/ and login fine

**Comment by kylewilliams321** [comment]
I added my site to the trusted origins in the config setup of add on. But I
keep getting the same error over and over agai ln when trying to access
through home assistant directly.

However it does work if I go directly to the ip address with the port that
I included.

This obviously means right now I can only access while on my home network.
Maybe another way to circumvent this as this is the whole reason I’m trying
to go through home assistant directly.

So it’s strange?

**Comment by Want100Cookies** [comment]
I too cannot make the addon work via Home Assistant's ingress feature. Accessing the addon via http://<ip>:8000/ works fine, but is cumbersome for my SO as it would only work when at home. I think I found the culprit, [you can only set a single cookie in the response at the moment.](https://github.com/home-assistant/supervisor/issues/4290). Can we perhaps do some nginx magic to only set a single cookie?

**Comment by wernerhp** [comment]
Got it working in like this
No space after `,`
```yaml
CSRF_TRUSTED_ORIGINS: >-
  https://ha.my.tld,https://ha.my.tld/hassio/ingress/68152197_baby_buddy,http://192.168.xx.1:8123
INGRESS_USER: admin
log_level: info
```

Network port set to 8000

Update: Looks like it only works locally. My app is set to the IP, not a domain. Domains don't work.  IP works, but only on LAN obv.
